### ISSUE TITLE
Pull Requests 

### ISSUE THREAD

**Issue by ngmachado** [tokencard/contracts#513]
I didn’t find documentation about this.

Do you accept pull requests?

**Comment by ngmachado** [comment]
If yes, how is the best way?

**Comment by i-stam** [comment]
Hi, we actually encourage people to inspect our code and  open issues, suggest improvements or find bugs. That's why the code is open source: feel free to fork  it, experiment with it and create a PR. We are definitely going to check it. 

Is there a specific issue you would like to address?

**Comment by ngmachado** [comment]
The whitelist addresses should have more functionality. 
They can act to protect assets if I lose control of my keys. I also think that they should form a social recovery mechanism to complement user protection.

**Comment by i-stam** [comment]
Thanks for the suggestions, these are things we have already put a lot of thought on and we are currently working on improving by providing extra functionality and a safe and user friendly recovery mechanism. However, Github (either via issues or PRs) is not the right place for such requests because they are not related to code improvement or fixes but mainly to product development. You are more than welcome of course to fork the code and experiment!
